### PR TITLE
Ft user registeration

### PR DESCRIPTION
**Pull request by Onyedikachi**
## Description
Setup user registration
Addresses issue  #(2)

## How Has This Been Tested?
The user registration endpoint was tested using the postman

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation

### CODE REVIEW

**Review by emydame — COMMENTED** [review]
Hi Kachi, kindly resolve the issue flagged by codacy on this pull request.

Thank you

**Review by victoryohanna — COMMENTED** [review]
app.js
{force : true} it drop all existing tables with all data and re-create new empty tables.You have new empty tables anytime server restart this leads to lost of information.

userCat.controller, userOrganization.controller, userPrivilege controller
You deleted (data), the endpoint is  promise based and data is the object to be returned so that request coming from the frontend will grab.

In user.route;
You changed app.post("/user", users.create); TO app.post("/user", users.register), users.create is callback function in sequelize just like findAll, findOne, update, delete etc
here is the resulting error "Error: Route.post() requires a callback function but got a [object Undefined]" 
In models;
You deleted comma(,) from last properties of some table elements, eslint automatically adds the commas according to Airbnb standard as soon as you save(CTRL-S) the file.
I advice that we create all required APIs before adding validation or authentication

**Review by victoryohanna — CHANGES_REQUESTED** [review]
We don't need npm packages that generate HTML such as HANDLEBARS the frontend guys will deal with that.

**Review by victoryohanna — CHANGES_REQUESTED** [review]
app.js
{force : true} it drop all existing tables with all data and re-create new empty tables.You have new empty tables anytime server restart this leads to lost of information.

**Review by victoryohanna — CHANGES_REQUESTED** [review]
app.post("/user", users.register)

**Review by MosesNwaeze — APPROVED** [review]

**Comment by Onyedikachi** [comment]
> app.js
> {force : true} it drop all existing tables with all data and re-create new empty tables.You have new empty tables anytime server restart this leads to lost of information.
> 
> userCat.controller, userOrganization.controller, userPrivilege controller
> You deleted (data), the endpoint is promise based and data is the object to be returned so that request coming from the frontend will grab.
> 
> In user.route;
> You changed app.post("/user", users.create); TO app.post("/user", users.register), users.create is callback function in sequelize just like findAll, findOne, update, delete etc
> here is the resulting error "Error: Route.post() requires a callback function but got a [object Undefined]"
> In models;
> You deleted comma(,) from last properties of some table elements, eslint automatically adds the commas according to Airbnb standard as soon as you save(CTRL-S) the file.
> I advice that we create all required APIs before adding validation or authentication

@victor, 

@{force : true}
the models you created needed to be adjusted. For now,  {force: true} should remain for development so as to have the same database structure while we work on the backend. It would be changed to {force: false} on production. Preferably you can change it to {force: false} when working locally.

@userCat.controller, userOrganization.controller, userPrivilege controller 
the data variable is not in use, by my eslint config you would have `no-used-vars` issue

@app.post("/user", users.create); TO app.post("/user", users.register)
Create user functionality is very basic, the model alone can handle that. With a register, every other business logic can be added aside just creating the user. That is why I replaced that logic.

@I advice that we create all required APIs before adding validation or authentication
I don't agree, remember we are racing against time. Adding just a create, update, delete to an API route will not help at this time.

@commas according to Airbnb standard as soon as you save(CTRL-S) the file
You must have configured your vscode for the Airbnb standard. However, this project uses the Airbnb base which does not enforce the trailing comma. I advise you to reconfigure, your local development environment.  Pls, check the .eslint.rc file in the project root to confirm my opinions. Thanks.

**Comment by Onyedikachi** [comment]
> app.js
> {force : true} it drop all existing tables with all data and re-create new empty tables.You have new empty tables anytime server restart this leads to lost of information.

Yes, the frontend guys can give us a better design for the email template. However, the template must be served by

**Comment by Onyedikachi** [comment]
> We don't need npm packages that generate HTML such as HANDLEBARS the frontend guys will deal with that.

Yes, the frontend guys can give us better design for the email template. Having an HTML templating system like handlebars is essential for our use case.

**Comment by Onyedikachi** [comment]
> We don't need npm packages that generate HTML such as HANDLEBARS the frontend guys will deal with that.

@victor
Yes, the frontend guys can give us better design for the email template. However, for our use case, an HTML templating system like handlebars is essential.

**Pull request closed without merging**
