### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by MosesNwaeze**
## Description
Created a viable project structure to be utilize by both frontend and backend developers
- the root package.json file has a script to run frontend code, backend code and both concurrently.
- use yarn frontend to run frontend, yarn backend to run backend, yarn start to run both
-  backend repo has a starting boiler plate code to kick start same as frontend repo
-  to install a new dependency cd into the repo. e.g cd src/frontent && yarn add axion
## How Has This Been Tested?
- yarn frontend to test frontend server
- yarn backend to test backend server
- yarn start to test both servers concurrently

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by elfizzy — DISMISSED** [review]
Reviewed and approved.

**Review by victoryohanna — DISMISSED** [review]
Well structured Backend directory

**Comment by Onyedikachi** [comment]
Nice work. Pls, review some of these trivial errors with codacy to improve the quality, https://app.codacy.com/gh/BuildForSDG/Team-028/pullRequest?prid=5498539. Eslint rules should be obeyed.

**Review by Onyedikachi — DISMISSED** [review]

**Review by elfizzy — DISMISSED** [review]
All checks passed and should be approved

**Review by Onyedikachi — DISMISSED** [review]

**Review by victoryohanna — CHANGES_REQUESTED** [review]
Reviewed

**Review by victoryohanna — DISMISSED** [review]
Reviewed

**Review by victoryohanna — APPROVED** [review]

**Review by emydame — APPROVED** [review]
Reviewed

**Review by elfizzy — APPROVED** [review]
Reviewed

**Comment by emydame** [comment]
Based on the resolution of the conflicts and positive review of this pull request by codacy, we are proceeding with the merger

**Pull request merged**
