### PR TITLE
Project-manangement-api-modified

### LINKED ISSUE #11: ft-Express API Routes Creation
**Is your feature request related to a problem? Please describe.**
The front-end application needs to communicate with the back-end to fulfill end-users request. Also, there is need for enforcing modularity in  the system design for ease of maintenance

**Describe the solution you'd like**
Creation of a Rest API to serve as a middle-ware to communicate with the back-end

**Describe alternatives you've considered**
Bundle the data access layer with the front-end modules

### PR DESCRIPTION
**Pull request by victoryohanna**
## Description
Modified project management APIs and added States and LGA data model

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Onyedikachi — APPROVED** [review]

**Review by fid37is — APPROVED** [review]
reviewed

**Review by emydame — COMMENTED** [review]
Reviewed

**Review by emydame — COMMENTED** [review]
Reviewed

**Review by emydame — APPROVED** [review]
Reviewed and Approved

**Pull request merged**
