### PR TITLE
Ft backend api modified

### PR DESCRIPTION
**Pull request by victoryohanna**
## Description
Modifies user category APIs

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation

### CODE REVIEW

**Review by emydame — COMMENTED** [review]
Hi Victor,

Kindly fix the errors flagged by codacy

**Review by fid37is — APPROVED** [review]

**Review by elfizzy — APPROVED** [review]
Reviewed

**Review by emydame — APPROVED** [review]
Reviewed

**Comment by emydame** [comment]
Based on the approval received from the team members and Codacy. This request is merged and closed

**Pull request merged**
