### PR TITLE
styled the login and register modals, please check and give feedback for work can continue

### LINKED ISSUE #43: ft: Enhance the look and feel of the modal pages
**Is your feature request related to a problem? Please describe.**
The existing modal pages (login, registration, contact us) needs to  be upgraded in style

**Describe the solution you'd like**
A touch of modernization and class in the modal components styling

**Describe alternatives you've considered**

### PR DESCRIPTION
**Pull request by fid37is**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by emydame — COMMENTED** [review]
There are issues with the pull request. Kindly review

**Comment by fid37is** [comment]
Done

**Review by elfizzy — APPROVED** [review]
Approved

**Review by emydame — APPROVED** [review]
Reviewed and approved

**Review by victoryohanna — APPROVED** [review]

**Pull request merged**
