### PR TITLE
Backend tests

### PR DESCRIPTION
**Pull request by Onyedikachi**
## Description
Added new tests for the following endpoints
- create user category
- create project category
- initiate fund disbursement 
- create project 
- create privileges
- initiate investment

Fixed security issue on the backend.

## How Has This Been Tested?
Running the following commands
yarn install on src/backend
yarn test

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests

### CODE REVIEW

**Comment by emydame** [comment]
HI Kachi,

This pull request is breaking standard. Kindly review

**Comment by Onyedikachi** [comment]
> HI Kachi,
> 
> This pull request is breaking standard. Kindly review

fixed

**Review by emydame — COMMENTED** [review]
Hi Kachi,

Kindly resolve the conflicts in the pull request to enable us proceed with the reviews.

Thank you

**Comment by Onyedikachi** [comment]
> Hi Kachi,
> 
> Kindly resolve the conflicts in the pull request to enable us proceed with the reviews.
> 
> Thank you

Resolved

**Review by victoryohanna — APPROVED** [review]

**Review by emydame — APPROVED** [review]
Reviewed

**Review by elfizzy — APPROVED** [review]

**Pull request merged**
